site_name: Developer Docs
site_url: https://norsk-gjeldsinformasjon.github.io/api-docs
repo_url: https://github.com/norsk-gjeldsinformasjon/api-docs
repo_name: api-docs

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - "stylesheets/extra.css"

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml
  - render_swagger
  - search

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Get started: get-started/index.md
  - How-to:
    - How-to: howto/index.md
    - Select an integration: "howto/1. Select an integration.md"
    - Authorize: "howto/2. How do I authorize.md"
    - Look up debt with consent: "howto/3. Lookup debt with consent.md"
    - Get notified about changes to consents: "howto/3.1 Get notified about consents.md"
    - Look up debt without consent: "howto/4. Lookup debt without consent.md"
    - Receive quarterly debt reports: "howto/5. Recieve quarterly debt reports.md"
    - Environments & endpoints: "howto/6. Environments & endpoints.md"
    - Contribute: howto/contributing.md
  - Deliver debt data:
    - Onboarding & scenarios: "howto/deliver/Onboarding_&_Scenarios.md"
    - Security requirements: howto/deliver/Security_requirements.md
    - API reference: howto/deliver/API_reference.md
    - Testing & go-live: "howto/deliver/Testing_&_go-live.md"
  - Reference:
    - Reference: reference/index.md
    - Consent reference: reference/consent.md
    - OpenAPI: reference/openapi.md
  - Explanations:
    - Explanations: explanation/index.md
    - Consent: explanation/consent.md
    - Consuming event feeds: explanation/consume-events-feed.md
